name: flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  http: ^0.13.6
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/megawati.jpg
    - assets/img/LogoKomatsu.png
    # - images/a_dot_ham.jpeg
    # example:
  fonts:
    - family: JosefinSansBold
      fonts:
        - asset: assets/font/JosefinSans-Bold.ttf
          style: italic
    - family: JosefinSansLight
      fonts:
        - asset: assets/font/JosefinSans-Light.ttf
          style: italic
